Platform.mods.kubejs.name = "Create"

// 0.5% chance mod names get funnyified
if (Math.random() < 0.05)
{
    let newNames = {
        grapplemod: "pew pew spiderman",
        betterdungeons: "woah these dungeons are nice",
        roughlyenoughprofessions: "now you know their jobs??",
        ftbessentials: "ESSENTIAL ftb stuff",
        supermartijn642configlib: "some config library idk",
        betterwitchhuts: "woah these witch huts are nice",
        satin: "shader stuff idk",
        betteroceanmonuments: "woah these ocean monuments are nice",
        connectivity: "fix the packets",
        sophisticatedcore: "very sophisticated mod",
        create_crush_everything: "CRUSH EVERYTHING USING CREATE HAHAHA",
        controlling: "CCOOONNTTRRROOOLLLL",
        modernfix: "fix yer performance",
        citadel: "library mod that is in every modpack istg",
        alexsmobs: "YEAAAHH ALEX'S MOBS",
        rei_plugin_compatibilities: "compatibilify my jei plugins please",
        jei: "just enough of my items, not too many though",
        yungsapi: "yung api",
        mixinextras: "extra mixins??",
        culinaryconstruct: "YEAAHHH CULINARY CONSTRUCT, I NEED MY SANDWICHES",
        bookshelf: "shelf for your books",
        sophisticatedbackpacks: "YEEAAHHH BACKPACKS",
        create_dragon_lib: "hey i could make a funny joke with this mod",
        railways: "YEAAAHH STEAM AND RAILS",
        balm: "dunno but it's in every modpack for some reason",
        betterfortresses: "woah these nether fortresses are nice",
        cloth_config: "configurate my cloths please",
        supplementaries: "supplement my mods",
        konkrete: "a very solid mod",
        embeddium: "a fork of a fork (with some patches)",
        rubidium: "performance!",
        advancementplaques: "YEEAAH ADVANCEMENT PLAQUES",
        w2w2: "xaero map compatibility",
        farmersdelight: "YEEEAAAHH FARMER'S DELIGHT",
        betterspawnercontrol: "control ALL the spawners",
        blur: "this is a pretty nice mod",
        supermartijn642corelib: "some gui stuff idk",
        yungsbridges: "woah there's bridges",
        collective: "collect the things",
        searchables: "search the stuff",
        yungsextras: "extra yung stuff??",
        framedblocks: "here you go builders, go wild",
        ftbultimine: "mine all the blocks",
        betterstrongholds: "woah these strongholds are nice",
        yungsmenutweaks: "woah these menus are nice",
        lootjs: "i can modify loot drops now",
        architectury: "architect's mod",
        aiimprovements: "improve the ai",
        cupboard: "idk what this mod does",
        betterendisland: "woah these end islands are nice",
        jadeaddons: "nice jade stuff?? idk",
        betterburning: "YEEEAAHH BETTER BURNING",
        probejs: "probe my javascript",
        fastleafdecay: "decay my leaves please",
        bettermineshafts: "woah these mineshafts are nice",
        crawlondemand: "crawly crawl",
        sliceanddice: "automate all of the farmer's delights",
        betterjungletemples: "woah these jungle temples are nice",
        betteradvancements: "woah these advancements are nice",
        bellsandwhistles: "nice create mod stuff??",
        rhino: "mozilla's rhino library? who knows what this is tbh",
        ftblibrary: "feed my libraries :)",
        ftbteams: "does anyone actually use this?",
        dice: "nice dice in my rice",
        rechiseled: "chisel (again)",
        waystones: "YEEAAAHH WAYSTONES",
        clumps: "my friend really likes this mod for no reason",
        comforts: "very comfortable mod",
        naturescompass: "find ALL the biomes",
        dungeoncrawl: "this is a pretty cool mod",
        rechiseledcreate: "chisel the create (again)",
        make_bubbles_pop: "pop all the bubbles",
        create_confectionery: "eww a mcreator mod (pretty good though)",
        betterdeserttemples: "woah these desert temples are nice",
        explorerscompass: "find ALL the structures",
        fusion: "fuse the textures idk",
        randomium: "very random",
        ftbchunks: "hey dont steal my stuff",
        createbb: "hehe funny create mod addon",
        craftingtweaks: "tweak the crafting",
        enchdesc: "no way now I know what the enchantments do",
        terrablender: "blend the terraria",
        biomesoplenty: "plenty of biomes",
        moonlight: "uhh some random library",
        mixinsquared: "square the mixins",
        jade: "no way now I know what that block is",
        spectrelib: "uhh some random library again",
        inventorio: "YEEAAHH INVENTORIO",
        roughlyenoughitems: "YEEEAAAHH REI",
        kubejs: "kube my javascript",
        betterfpsdist: "more fps",
        kotlinforforge: "kotlin (but for forge!)",
        iceberg: "uhh some random library again again",
        flywheel: "some library that create wants",
        create: "uhh some random mod idk",
        ponderjs: "ponder my javascript",
        create_sa: "eww mcreator mod (but it's actually not bad)",
        better_rubber: "yeah now my rubber is good",
        polymorph: "morph my polygons",
        immersive_paintings: "these are some pretty cool paintings",
        entityculling: "more fps i guess",
        betterchunkloading: "load my chunks (but better)",
        xaeroplus: "more xaero stuff",
        xaerosworldmap: "map my world",
        xaerosminimap: "map my world (but smaller)",
        kubejs_create: "create all my javascript kubes",
        appleskin: "peel my apples",
        lootr: "YEEAAAHH LOOTR",
        ferritecore: "you need to download more ram",
        justzoom: "zoomy zoom",
        betterf3: "F3 (but better)",
        aquaculture: "culture of the aqua",
        create_enchantment_industry: "automatic enchanting?? pretty cool mod",
        loadmyresources: "LOAD MY RESOURCES NOW"
    }

    for (let [k, v] of Object.entries(newNames))
    {
        console.log(k, v)
        Platform.mods[k].name = v
    }
}
